pluginManagement {
    includeBuild("build-logic")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "AstrBotAndroidNative"
include(":app")
include(":app-integration")
include(":architecture-tests")
include(":core:common")
include(":core:backup")
include(":core:db")
include(":core:logging")
include(":core:network")
include(":core:runtime")
include(":core:runtime-audio")
include(":core:runtime-cache")
include(":core:runtime-container")
include(":core:runtime-context")
include(":core:runtime-llm")
include(":core:runtime-search")
include(":core:runtime-secret")
include(":core:runtime-session")
include(":core:runtime-tool")
include(":core:ui")
include(":download:api")
include(":download:impl")
include(":feature:bot:api")
include(":feature:bot:data")
include(":feature:bot:impl")
include(":feature:bot:presentation")
include(":feature:chat:api")
include(":feature:chat:impl")
include(":feature:chat:presentation")
include(":feature:chat:runtime")
include(":feature:config:api")
include(":feature:config:data")
include(":feature:config:impl")
include(":feature:config:presentation")
include(":feature:conversation:api")
include(":feature:conversation:data")
include(":feature:cron:api")
include(":feature:cron:data")
include(":feature:cron:impl")
include(":feature:cron:presentation")
include(":feature:cron:runtime")
include(":feature:persona:api")
include(":feature:persona:data")
include(":feature:persona:impl")
include(":feature:persona:presentation")
include(":feature:plugin:api")
include(":feature:plugin:data")
include(":feature:plugin:impl")
include(":feature:plugin:presentation")
include(":feature:plugin:runtime")
include(":feature:provider:api")
include(":feature:provider:data")
include(":feature:provider:impl")
include(":feature:provider:presentation")
include(":feature:provider:runtime")
include(":feature:qq:api")
include(":feature:qq:data")
include(":feature:qq:impl")
include(":feature:qq:presentation")
include(":feature:qq:runtime")
include(":feature:resource:api")
include(":feature:resource:data")
include(":feature:resource:impl")
include(":feature:resource:presentation")
include(":feature:settings:api")
include(":feature:settings:presentation")
include(":feature:voiceasset:api")
include(":feature:voiceasset:data")
include(":feature:voiceasset:presentation")
