package com.astrbot.android.core.runtime.audio

internal data class TtsStyleHints(
    val openAiInstruction: String = "",
    val dashScopeInstruction: String = "",
    val miniMaxEmotion: String? = null,
    val miniMaxTags: List<String> = emptyList(),
)

internal data class TtsStyleMapping(
    val priority: Int,
    val keywords: List<String>,
    val openAiInstruction: String? = null,
    val dashScopeInstruction: String? = null,
    val miniMaxEmotion: String? = null,
    val miniMaxTags: List<String> = emptyList(),
)

internal object TtsStyleMappings {
    val entries = listOf(
        TtsStyleMapping(
            priority = 120,
            keywords = listOf("温柔", "温和", "柔和", "柔声", "轻柔", "轻声", "轻轻", "和缓"),
            openAiInstruction = "a warm, gentle, soft tone",
            dashScopeInstruction = "温柔轻柔、语气放软",
            miniMaxEmotion = "neutral",
        ),
        TtsStyleMapping(
            priority = 118,
            keywords = listOf("安抚", "安慰", "哄", "治愈", "抚慰", "宽慰"),
            openAiInstruction = "a soothing and comforting delivery",
            dashScopeInstruction = "安抚感强、带陪伴感",
            miniMaxEmotion = "neutral",
        ),
        TtsStyleMapping(
            priority = 116,
            keywords = listOf("冷静", "平静", "淡定", "沉着", "克制"),
            openAiInstruction = "a calm and composed delivery",
            dashScopeInstruction = "冷静克制、稳定沉着",
            miniMaxEmotion = "neutral",
        ),
        TtsStyleMapping(
            priority = 114,
            keywords = listOf("认真", "严肃", "郑重", "正式", "专业"),
            openAiInstruction = "a serious, focused, professional tone",
            dashScopeInstruction = "认真正式、表达清晰",
            miniMaxEmotion = "neutral",
        ),
        TtsStyleMapping(
            priority = 112,
            keywords = listOf("坚定", "果断", "斩钉截铁", "强硬"),
            openAiInstruction = "a firm and decisive tone",
            dashScopeInstruction = "坚定有力、态度明确",
            miniMaxEmotion = "angry",
        ),
        TtsStyleMapping(
            priority = 110,
            keywords = listOf("开心", "高兴", "喜悦", "愉快", "雀跃", "元气", "欢快", "轻快"),
            openAiInstruction = "a cheerful, upbeat, lively tone",
            dashScopeInstruction = "轻快明亮、带愉悦感",
            miniMaxEmotion = "happy",
        ),
        TtsStyleMapping(
            priority = 108,
            keywords = listOf("活泼", "俏皮", "调皮", "可爱", "撒娇", "甜甜", "软萌"),
            openAiInstruction = "a playful, cute, slightly teasing tone",
            dashScopeInstruction = "俏皮可爱、带一点撒娇感",
            miniMaxEmotion = "happy",
            miniMaxTags = listOf("(emm)"),
        ),
        TtsStyleMapping(
            priority = 106,
            keywords = listOf("兴奋", "激动", "热情", "振奋", "亢奋"),
            openAiInstruction = "an excited, energetic, animated delivery",
            dashScopeInstruction = "热情高涨、情绪明显上扬",
            miniMaxEmotion = "happy",
            miniMaxTags = listOf("(gasps)"),
        ),
        TtsStyleMapping(
            priority = 104,
            keywords = listOf("害羞", "腼腆", "不好意思", "羞涩"),
            openAiInstruction = "a shy, hesitant, softened tone",
            dashScopeInstruction = "带一点害羞和迟疑感",
            miniMaxEmotion = "fearful",
            miniMaxTags = listOf("(emm)"),
        ),
        TtsStyleMapping(
            priority = 102,
            keywords = listOf("紧张", "慌张", "不安", "局促"),
            openAiInstruction = "a tense and uneasy tone with slight hesitation",
            dashScopeInstruction = "紧张不安、略带迟疑",
            miniMaxEmotion = "fearful",
            miniMaxTags = listOf("(gasps)", "(pant)"),
        ),
        TtsStyleMapping(
            priority = 100,
            keywords = listOf("害怕", "恐惧", "惊恐", "发怵"),
            openAiInstruction = "a fearful, shaken tone",
            dashScopeInstruction = "害怕发紧、情绪发颤",
            miniMaxEmotion = "fearful",
            miniMaxTags = listOf("(gasps)", "(inhale)"),
        ),
        TtsStyleMapping(
            priority = 98,
            keywords = listOf("惊讶", "震惊", "诧异", "吃惊"),
            openAiInstruction = "a surprised and reactive tone",
            dashScopeInstruction = "带明显惊讶感、语调抬起",
            miniMaxEmotion = "surprised",
            miniMaxTags = listOf("(gasps)"),
        ),
        TtsStyleMapping(
            priority = 96,
            keywords = listOf("难过", "伤心", "悲伤", "低落", "失落", "委屈"),
            openAiInstruction = "a sad, subdued, emotionally heavy tone",
            dashScopeInstruction = "低落伤感、情绪下沉",
            miniMaxEmotion = "sad",
            miniMaxTags = listOf("(sighs)"),
        ),
        TtsStyleMapping(
            priority = 94,
            keywords = listOf("哽咽", "抽泣", "哭腔", "带哭", "哭"),
            openAiInstruction = "a choked, tearful voice with trembling emotion",
            dashScopeInstruction = "带哽咽和抽泣感、情绪脆弱",
            miniMaxEmotion = "sad",
            miniMaxTags = listOf("(crying)", "(sniffs)"),
        ),
        TtsStyleMapping(
            priority = 92,
            keywords = listOf("生气", "愤怒", "火大", "暴躁"),
            openAiInstruction = "an angry, forceful tone",
            dashScopeInstruction = "压不住火气、语气更重",
            miniMaxEmotion = "angry",
            miniMaxTags = listOf("(snorts)", "(hissing)"),
        ),
        TtsStyleMapping(
            priority = 90,
            keywords = listOf("不耐烦", "嫌弃", "烦躁", "恼火"),
            openAiInstruction = "an impatient and irritated tone",
            dashScopeInstruction = "明显不耐烦、略带嫌弃",
            miniMaxEmotion = "angry",
            miniMaxTags = listOf("(snorts)"),
        ),
        TtsStyleMapping(
            priority = 88,
            keywords = listOf("冷淡", "冷冷", "疏离", "冰冷"),
            openAiInstruction = "a cold, distant, restrained tone",
            dashScopeInstruction = "冷淡疏离、情绪收着说",
            miniMaxEmotion = "neutral",
        ),
        TtsStyleMapping(
            priority = 86,
            keywords = listOf("疲惫", "疲倦", "累", "无力", "虚弱", "病弱"),
            openAiInstruction = "a tired, weak, breathy delivery",
            dashScopeInstruction = "疲惫虚弱、气息偏轻",
            miniMaxEmotion = "sad",
            miniMaxTags = listOf("(breath)", "(sighs)"),
        ),
        TtsStyleMapping(
            priority = 84,
            keywords = listOf("低声", "耳语", "小声", "悄悄"),
            openAiInstruction = "a soft whispering delivery",
            dashScopeInstruction = "低声耳语、尽量贴近耳边说话感",
            miniMaxEmotion = "neutral",
            miniMaxTags = listOf("(breath)", "(exhale)"),
        ),
        TtsStyleMapping(
            priority = 82,
            keywords = listOf("神秘", "意味深长", "幽幽", "诡异"),
            openAiInstruction = "a mysterious, hushed, evocative tone",
            dashScopeInstruction = "神秘含蓄、留有余味",
            miniMaxEmotion = "neutral",
            miniMaxTags = listOf("(breath)"),
        ),
        TtsStyleMapping(
            priority = 80,
            keywords = listOf("轻笑", "偷笑", "含笑", "微笑"),
            openAiInstruction = "a smiling delivery with a soft chuckle",
            dashScopeInstruction = "带轻笑感、嘴角带笑",
            miniMaxEmotion = "happy",
            miniMaxTags = listOf("(chuckle)"),
        ),
        TtsStyleMapping(
            priority = 78,
            keywords = listOf("大笑", "哈哈", "爆笑", "笑出声"),
            openAiInstruction = "a laughing, openly amused delivery",
            dashScopeInstruction = "明显笑出声、情绪外放",
            miniMaxEmotion = "happy",
            miniMaxTags = listOf("(laughs)"),
        ),
        TtsStyleMapping(
            priority = 76,
            keywords = listOf("叹气", "轻叹", "叹息"),
            openAiInstruction = "a sighing, resigned delivery",
            dashScopeInstruction = "先带叹息感，再说正文",
            miniMaxTags = listOf("(sighs)"),
        ),
        TtsStyleMapping(
            priority = 74,
            keywords = listOf("吸鼻子", "鼻音", "抽鼻子"),
            openAiInstruction = "a sniffing, slightly nasal delivery",
            dashScopeInstruction = "带轻微吸鼻子的感觉",
            miniMaxTags = listOf("(sniffs)"),
        ),
        TtsStyleMapping(
            priority = 72,
            keywords = listOf("喘", "喘气", "喘息"),
            openAiInstruction = "a breathless, panting delivery",
            dashScopeInstruction = "气息更急、像在喘息",
            miniMaxTags = listOf("(pant)"),
        ),
        TtsStyleMapping(
            priority = 70,
            keywords = listOf("吸气", "倒吸气", "吸了一口气"),
            openAiInstruction = "an inhaled pre-utterance and tightened delivery",
            dashScopeInstruction = "先有吸气感，再进入正文",
            miniMaxTags = listOf("(inhale)"),
        ),
        TtsStyleMapping(
            priority = 68,
            keywords = listOf("呼气", "吐气", "缓缓呼气"),
            openAiInstruction = "a released-breath, softened delivery",
            dashScopeInstruction = "先轻轻呼气，再说正文",
            miniMaxTags = listOf("(exhale)"),
        ),
        TtsStyleMapping(
            priority = 66,
            keywords = listOf("咳", "咳嗽"),
            openAiInstruction = "include a brief cough before speaking",
            dashScopeInstruction = "带一声轻咳后再说",
            miniMaxTags = listOf("(coughs)"),
        ),
        TtsStyleMapping(
            priority = 64,
            keywords = listOf("清嗓", "清清嗓子", "清嗓子"),
            openAiInstruction = "clear the throat briefly before speaking",
            dashScopeInstruction = "先清一下嗓子，再说正文",
            miniMaxTags = listOf("(clear-throat)"),
        ),
        TtsStyleMapping(
            priority = 62,
            keywords = listOf("呻吟", "闷哼", "难受地哼"),
            openAiInstruction = "a strained groan before speaking",
            dashScopeInstruction = "带一点难受的闷哼感",
            miniMaxTags = listOf("(groans)"),
        ),
        TtsStyleMapping(
            priority = 60,
            keywords = listOf("哼唱", "哼着", "轻哼"),
            openAiInstruction = "a lightly humming delivery",
            dashScopeInstruction = "带一点轻哼或哼唱感",
            miniMaxTags = listOf("(humming)"),
        ),
        TtsStyleMapping(
            priority = 58,
            keywords = listOf("咂嘴", "撇嘴"),
            openAiInstruction = "a lip-smacking, slightly dismissive delivery",
            dashScopeInstruction = "带一点咂嘴的小动作",
            miniMaxTags = listOf("(lip-smacking)"),
        ),
        TtsStyleMapping(
            priority = 56,
            keywords = listOf("喷鼻息", "哼鼻", "嗤之以鼻"),
            openAiInstruction = "a snorting, dismissive delivery",
            dashScopeInstruction = "带一点喷鼻息和不屑感",
            miniMaxTags = listOf("(snorts)"),
        ),
        TtsStyleMapping(
            priority = 54,
            keywords = listOf("嘶", "嘶嘶", "倒抽冷气"),
            openAiInstruction = "a hissed, sharp-edged delivery",
            dashScopeInstruction = "带一点压低的嘶声",
            miniMaxTags = listOf("(hissing)"),
        ),
        TtsStyleMapping(
            priority = 52,
            keywords = listOf("喷嚏", "打喷嚏"),
            openAiInstruction = "include a sneeze-like break before speaking",
            dashScopeInstruction = "像刚打完喷嚏一样接着说",
            miniMaxTags = listOf("(sneezes)"),
        ),
        TtsStyleMapping(
            priority = 50,
            keywords = listOf("鼓掌", "拍手"),
            openAiInstruction = "a celebratory delivery with applause-like energy",
            dashScopeInstruction = "带庆贺和鼓掌般的热烈感",
            miniMaxEmotion = "happy",
            miniMaxTags = listOf("(applause)"),
        ),
    )
}
