#!/system/bin/sh

APP_HOME="$1"
if [ -z "$APP_HOME" ]; then
  echo "APP_HOME argument is required" >&2
  exit 1
fi

NATIVE_LIB_DIR="${2:-}"
if [ -z "$NATIVE_LIB_DIR" ]; then
  echo "NATIVE_LIB_DIR argument is required" >&2
  exit 1
fi

RUNTIME_DIR="$APP_HOME/runtime"
BIN_DIR="$RUNTIME_DIR/bin"
SCRIPT_DIR="$RUNTIME_DIR/scripts"
VAR_DIR="$RUNTIME_DIR/var"
LOG_DIR="$RUNTIME_DIR/logs"
RUN_DIR="$RUNTIME_DIR/run"
ROOTFS_DIR="$RUNTIME_DIR/rootfs/ubuntu"
ROOT_HOME_DIR="$ROOTFS_DIR/root"
PACKAGE_DIR="$(dirname "$APP_HOME")"
PACKAGE_NAME="$(basename "$PACKAGE_DIR")"
DATA_COMPAT_DIR="/data/data/$PACKAGE_NAME/files"
USR_COMPAT_DIR="$DATA_COMPAT_DIR/usr"
TMP_COMPAT_DIR="$USR_COMPAT_DIR/tmp"
HOME_COMPAT_DIR="$DATA_COMPAT_DIR/home"
PID_FILE="$RUN_DIR/napcat.pid"
LOG_FILE="$LOG_DIR/napcat.log"
PROGRESS_FILE="$RUN_DIR/napcat_progress"
PROGRESS_LABEL_FILE="$RUN_DIR/napcat_progress_label"
PROGRESS_MODE_FILE="$RUN_DIR/napcat_progress_mode"
INSTALLER_CACHE_FILE="$RUN_DIR/napcat_installer_cached"
PROOT_BIN="$BIN_DIR/proot"
BUSYBOX_BIN="$BIN_DIR/busybox"
LOADER_BIN="$BIN_DIR/loader"
UBUNTU_ARCHIVE="$RUNTIME_DIR/assets/ubuntu-rootfs.tar.xz"

mkdir -p "$BIN_DIR" "$SCRIPT_DIR" "$VAR_DIR" "$LOG_DIR" "$RUN_DIR" "$RUNTIME_DIR/assets" "$ROOT_HOME_DIR" "$USR_COMPAT_DIR" "$TMP_COMPAT_DIR" "$HOME_COMPAT_DIR"

export APP_HOME NATIVE_LIB_DIR RUNTIME_DIR BIN_DIR SCRIPT_DIR VAR_DIR LOG_DIR RUN_DIR ROOTFS_DIR ROOT_HOME_DIR PACKAGE_DIR PACKAGE_NAME DATA_COMPAT_DIR USR_COMPAT_DIR TMP_COMPAT_DIR HOME_COMPAT_DIR PID_FILE LOG_FILE PROGRESS_FILE PROGRESS_LABEL_FILE PROGRESS_MODE_FILE INSTALLER_CACHE_FILE PROOT_BIN BUSYBOX_BIN LOADER_BIN UBUNTU_ARCHIVE
export PROOT_LOADER="$LOADER_BIN"
export PROOT_TMP_DIR="$TMP_COMPAT_DIR"
export LD_LIBRARY_PATH="$BIN_DIR:$NATIVE_LIB_DIR"
export TERMUX_PREFIX="$USR_COMPAT_DIR"
export HOME="$HOME_COMPAT_DIR"

if [ -n "${ASTRBOT_PROOT_NO_SECCOMP:-}" ]; then
  export PROOT_NO_SECCOMP="$ASTRBOT_PROOT_NO_SECCOMP"
else
  unset PROOT_NO_SECCOMP 2>/dev/null || true
fi
