package com.astrbot.android.runtime

import android.content.Context
import java.io.File
import java.nio.charset.StandardCharsets
import java.security.SecureRandom

object RuntimeSecretRepository {
    data class RuntimeSecrets(
        val webUiToken: String,
        val webUiJwtSecret: String,
    )

    private const val SECRET_VERSION = "1"
    private const val CONFIG_DIR_NAME = "config"
    private const val SECRET_FILE_NAME = "runtime-secrets.env"
    private const val SECRET_BYTE_SIZE = 32

    @Volatile
    private var appContext: Context? = null

    @Volatile
    private var secretsOverrideForTests: RuntimeSecrets? = null

    private val lock = Any()

    fun initialize(context: Context) {
        appContext = context.applicationContext
        getOrCreateSecrets()
    }

    fun getOrCreateSecrets(): RuntimeSecrets {
        secretsOverrideForTests?.let { return it }
        val context = appContext ?: throw IllegalStateException("RuntimeSecretRepository is not initialized.")
        return synchronized(lock) {
            loadOrCreateSecrets(runtimeRootDir(context.filesDir)) { size ->
                ByteArray(size).also(SecureRandom()::nextBytes)
            }
        }
    }

    fun getOrCreateWebUiToken(): String = getOrCreateSecrets().webUiToken

    fun getOrCreateWebUiJwtSecret(): String = getOrCreateSecrets().webUiJwtSecret

    internal fun setSecretsOverrideForTests(secrets: RuntimeSecrets?) {
        secretsOverrideForTests = secrets
    }

    internal fun loadOrCreateSecretsForTests(
        rootDir: File,
        randomBytes: (Int) -> ByteArray,
    ): RuntimeSecrets {
        return synchronized(lock) {
            loadOrCreateSecrets(rootDir, randomBytes)
        }
    }

    private fun loadOrCreateSecrets(
        rootDir: File,
        randomBytes: (Int) -> ByteArray,
    ): RuntimeSecrets {
        val secretFile = secretFile(rootDir)
        parseSecrets(secretFile)?.let {
            RuntimeLogRepository.append(
                "Runtime secrets ready: source=persisted tokenLength=${it.webUiToken.length} jwtLength=${it.webUiJwtSecret.length}",
            )
            return it
        }

        val generated = RuntimeSecrets(
            webUiToken = randomBytes(SECRET_BYTE_SIZE).toHexString(),
            webUiJwtSecret = randomBytes(SECRET_BYTE_SIZE).toHexString(),
        )
        writeSecrets(secretFile, generated)
        RuntimeLogRepository.append(
            "Runtime secrets ready: source=generated tokenLength=${generated.webUiToken.length} jwtLength=${generated.webUiJwtSecret.length}",
        )
        return generated
    }

    private fun parseSecrets(secretFile: File): RuntimeSecrets? {
        if (!secretFile.isFile) return null
        val entries = secretFile.readLines(StandardCharsets.UTF_8)
            .map(String::trim)
            .filter { it.isNotBlank() && !it.startsWith("#") }
            .mapNotNull { line ->
                val separator = line.indexOf('=')
                if (separator <= 0) return@mapNotNull null
                line.substring(0, separator).trim() to line.substring(separator + 1).trim()
            }
            .toMap()

        val token = entries["NAPCAT_WEBUI_SECRET_KEY"].orEmpty()
        val jwtSecret = entries["NAPCAT_WEBUI_JWT_SECRET_KEY"].orEmpty()
        if (!token.isValidSecret() || !jwtSecret.isValidSecret()) {
            return null
        }
        return RuntimeSecrets(
            webUiToken = token,
            webUiJwtSecret = jwtSecret,
        )
    }

    private fun writeSecrets(secretFile: File, secrets: RuntimeSecrets) {
        secretFile.parentFile?.mkdirs()
        secretFile.writeText(
            buildString {
                appendLine("# Generated by ElymBot. Do not edit while the app is running.")
                appendLine("ASTRBOT_RUNTIME_SECRET_VERSION=$SECRET_VERSION")
                appendLine("NAPCAT_WEBUI_SECRET_KEY=${secrets.webUiToken}")
                appendLine("NAPCAT_WEBUI_JWT_SECRET_KEY=${secrets.webUiJwtSecret}")
            },
            StandardCharsets.UTF_8,
        )
    }

    private fun runtimeRootDir(filesDir: File): File {
        return File(filesDir, "runtime")
    }

    private fun secretFile(rootDir: File): File {
        return File(File(rootDir, CONFIG_DIR_NAME), SECRET_FILE_NAME)
    }

    private fun ByteArray.toHexString(): String {
        return joinToString(separator = "") { byte -> "%02x".format(byte) }
    }

    private fun String.isValidSecret(): Boolean {
        return length == SECRET_BYTE_SIZE * 2 && all { it in '0'..'9' || it in 'a'..'f' }
    }
}
