package com.astrbot.android.feature.config.domain.model

import com.astrbot.android.model.McpServerEntry
import com.astrbot.android.model.SkillEntry

data class ConfigProfile(
    val id: String = "",
    val name: String = "",
    val defaultChatProviderId: String = "",
    val defaultVisionProviderId: String = "",
    val defaultSttProviderId: String = "",
    val defaultTtsProviderId: String = "",
    val sttEnabled: Boolean = false,
    val ttsEnabled: Boolean = false,
    val alwaysTtsEnabled: Boolean = false,
    val ttsReadBracketedContent: Boolean = true,
    val textStreamingEnabled: Boolean = false,
    val voiceStreamingEnabled: Boolean = false,
    val streamingMessageIntervalMs: Int = 120,
    val realWorldTimeAwarenessEnabled: Boolean = false,
    val imageCaptionTextEnabled: Boolean = false,
    val webSearchEnabled: Boolean = false,
    val proactiveEnabled: Boolean = false,
    val includeScheduledTaskConversationContext: Boolean = false,
    val ttsVoiceId: String = "",
    val imageCaptionPrompt: String = "Describe the image in detail before sending it to the chat model.",
    val adminUids: List<String> = emptyList(),
    val sessionIsolationEnabled: Boolean = false,
    val wakeWords: List<String> = emptyList(),
    val wakeWordsAdminOnlyEnabled: Boolean = false,
    val privateChatRequiresWakeWord: Boolean = false,
    val replyTextPrefix: String = "",
    val quoteSenderMessageEnabled: Boolean = false,
    val mentionSenderEnabled: Boolean = false,
    val replyOnAtOnlyEnabled: Boolean = true,
    val whitelistEnabled: Boolean = false,
    val whitelistEntries: List<String> = emptyList(),
    val logOnWhitelistMiss: Boolean = false,
    val adminGroupBypassWhitelistEnabled: Boolean = true,
    val adminPrivateBypassWhitelistEnabled: Boolean = true,
    val ignoreSelfMessageEnabled: Boolean = true,
    val ignoreAtAllEventEnabled: Boolean = true,
    val replyWhenPermissionDenied: Boolean = false,
    val rateLimitWindowSeconds: Int = 0,
    val rateLimitMaxCount: Int = 0,
    val rateLimitStrategy: String = "drop",
    val keywordDetectionEnabled: Boolean = false,
    val keywordPatterns: List<String> = emptyList(),
    val contextLimitStrategy: String = "truncate_by_turns",
    val maxContextTurns: Int = -1,
    val dequeueContextTurns: Int = 1,
    val llmCompressInstruction: String = "",
    val llmCompressKeepRecent: Int = 6,
    val llmCompressProviderId: String = "",
    val mcpServers: List<McpServerEntry> = emptyList(),
    val skills: List<SkillEntry> = emptyList(),
)
