plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
    id("com.google.devtools.ksp")
    id("com.google.dagger.hilt.android")
}

android {
    namespace = "com.astrbot.android.app.integration"
}

dependencies {
    val roomVersion = "2.6.1"

    api(project(":core:common"))
    implementation(project(":core:backup"))
    api(project(":core:db"))
    api(project(":core:logging"))
    api(project(":core:network"))
    api(project(":core:runtime"))
    api(project(":core:runtime-audio"))
    api(project(":core:runtime-cache"))
    api(project(":core:runtime-container"))
    api(project(":core:runtime-context"))
    api(project(":core:runtime-llm"))
    api(project(":core:runtime-search"))
    api(project(":core:runtime-secret"))
    api(project(":core:runtime-session"))
    api(project(":core:runtime-tool"))
    api(project(":download:api"))
    api(project(":download:impl"))
    api(project(":feature:bot:api"))
    api(project(":feature:bot:data"))
    api(project(":feature:bot:impl"))
    api(project(":feature:chat:api"))
    api(project(":feature:chat:impl"))
    api(project(":feature:conversation:api"))
    api(project(":feature:conversation:data"))
    api(project(":feature:config:api"))
    api(project(":feature:config:data"))
    api(project(":feature:config:impl"))
    api(project(":feature:cron:api"))
    api(project(":feature:cron:data"))
    api(project(":feature:cron:impl"))
    api(project(":feature:cron:runtime"))
    api(project(":feature:persona:api"))
    api(project(":feature:persona:data"))
    api(project(":feature:persona:impl"))
    api(project(":feature:plugin:api"))
    implementation(project(":feature:plugin:data"))
    implementation(project(":feature:plugin:runtime"))
    api(project(":feature:provider:api"))
    api(project(":feature:provider:data"))
    api(project(":feature:provider:impl"))
    api(project(":feature:qq:api"))
    implementation(project(":feature:qq:data"))
    implementation(project(":feature:qq:impl"))
    implementation(project(":feature:qq:runtime"))
    api(project(":feature:resource:api"))
    api(project(":feature:resource:data"))
    api(project(":feature:resource:impl"))
    implementation("androidx.room:room-runtime:$roomVersion")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1")
    implementation("javax.inject:javax.inject:1")
    implementation("com.google.dagger:hilt-android:2.52")
    ksp("com.google.dagger:hilt-compiler:2.52")
}
